apiVersion: v1
entries:
  actions-runner-controller:
  - apiVersion: v2
    appVersion: 0.26.0
    created: "2022-10-21T10:52:59.88536213Z"
    description: A Kubernetes controller that operates self-hosted runners for GitHub
      Actions on your Kubernetes cluster.
    digest: a36fbe9956b2f4c252bfdc6a4693dfc9e9b4565e0387086bd2a309e4005b109e
    home: https://github.com/actions-runner-controller/actions-runner-controller
    maintainers:
    - name: actions-runner-controller
      url: https://github.com/actions-runner-controller
    name: actions-runner-controller
    sources:
    - https://github.com/actions-runner-controller/actions-runner-controller
    type: application
    urls:
    - actions-runner-controller-0.21.0.tgz
    version: 0.21.0
generated: "2022-10-21T10:52:59.875605003Z"
