{{- if .Values.podDisruptionBudget.enabled }}
{{- if semverCompare "<1.21-0" (include "common.capabilities.kubeVersion" .) -}}
apiVersion: policy/v1beta1
{{- else -}}
apiVersion: policy/v1
{{- end -}}
kind: PodDisruptionBudget
metadata:
  labels:
    {{- include "actions-runner-controller.labels" . | nindent 4 }}
  name: {{ include "actions-runner-controller.pdbName" . }}
  namespace: {{ .Release.Namespace }}
spec:
  {{- if .Values.podDisruptionBudget.minAvailable }}
  minAvailable: {{ .Values.podDisruptionBudget.minAvailable }}
  {{- end  }}
  {{- if .Values.podDisruptionBudget.maxUnavailable }}
  maxUnavailable: {{ .Values.podDisruptionBudget.maxUnavailable }}
  {{- end  }}
  selector:
    matchLabels:
      {{- include "actions-runner-controller.selectorLabels" . | nindent 6 }}
{{- end -}}
